### ISSUE TITLE
Greek letters

### ISSUE THREAD

**Issue by Dimitrees** [tushartushar/theGreekLegacy#1]
All Greek letters are not appearing properly. Someone know a fix for this?

**Comment by gpantelis** [comment]
maybe we need to change the encoding? to UTF-8?

**Comment by Dimitrees** [comment]
![image](https://cloud.githubusercontent.com/assets/15691073/24555738/daa96a8c-163a-11e7-9271-d7c10556c65f.png)
 It seems that the character encoding is set to UTF-8, but still the result is not correct.

**Comment by gpantelis** [comment]
When i try to edit the file 
![aaa](https://cloud.githubusercontent.com/assets/15388689/24565749/48dd5bb6-165f-11e7-8aa8-d061619391d3.PNG)

**Comment by Dimitrees** [comment]
I have commited changes to the file, and the encoding had obviously been set to UTF-8. However the problem remains.

**Comment by tushartushar** [comment]
Fixed.
